### PR TITLE
remove ESM, fallback to UMD or CJS

### PR DESCRIPTION
**Pull request by k1r0s**
@alexjoverm comments?

### CODE REVIEW

**Comment by k1r0s** [comment]
IMO best approach is to change source code to use ESM directly and then, point package.json "module" entry to src/index.js, then module-aware tools like rollup, webpack 2, and some browsers will use it directly.

**Comment by mkatrenik** [comment]
Why not export items separately?
```
export {
  clear,
  override
  ...
}
```

**Comment by k1r0s** [comment]
esm file is auto-generated, I cannot edit it.

That's why im suggesting to tweak the source to use esm directly rather than cjs

**Comment by mkatrenik** [comment]
Ah, ok, I didn't realize you use commonjs export in source file, so then yes, this makes sense.

**Comment by alexjoverm** [comment]
@k1r0s I think what @mkatrenik was asking for in #9 is another thing. The bundler config as it was is ok.

What @mkatrenik asked is to export the library using named exports (in separate functions), so modern bundlers can make use of Tree Shaking in order to remove unused code.

So, I'd say this PR seems not relevant to #9

**Comment by k1r0s** [comment]
Thanks @alexjoverm, I do get @mkatrenik 's point about it, but since esm file is autogenerated I don't know how to force rollup to correctly create named exports...

I should do something like this?

```
module.exports.createClass = main.createClass;
module.exports.extend = main.extend;
module.exports.clear = main.clear;
module.exports.override = main.inject;
module.exports.provider = main.provider;
module.exports.reflect = main.reflect;

```

**Comment by k1r0s** [comment]
already tested second approach and I think its correct as @alexjoverm points too:

this is kaop.esm.js generated file 

```
export { createClass, extend$1 as extend, clear$1 as clear, override_1$1 as override, provider_1$1 as provider, reflect_1$1 as reflect };
```

**Comment by k1r0s** [comment]
thanks floks! https://github.com/k1r0s/kaop/pull/11

**Pull request closed without merging**
